/**
 */
package rEMODEL.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import rEMODEL.util.REMODELAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class REMODELItemProviderAdapterFactory extends REMODELAdapterFactory
		implements ComposeableAdapterFactory, IChangeNotifier {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public REMODELItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.RequirementModel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RequirementModelItemProvider requirementModelItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.RequirementModel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRequirementModelAdapter() {
		if (requirementModelItemProvider == null) {
			requirementModelItemProvider = new RequirementModelItemProvider(this);
		}

		return requirementModelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.Interaction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InteractionItemProvider interactionItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.Interaction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInteractionAdapter() {
		if (interactionItemProvider == null) {
			interactionItemProvider = new InteractionItemProvider(this);
		}

		return interactionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.MessageNew} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MessageNewItemProvider messageNewItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.MessageNew}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMessageNewAdapter() {
		if (messageNewItemProvider == null) {
			messageNewItemProvider = new MessageNewItemProvider(this);
		}

		return messageNewItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.CallMessage} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CallMessageItemProvider callMessageItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.CallMessage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCallMessageAdapter() {
		if (callMessageItemProvider == null) {
			callMessageItemProvider = new CallMessageItemProvider(this);
		}

		return callMessageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.ReturnMessage} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReturnMessageItemProvider returnMessageItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.ReturnMessage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReturnMessageAdapter() {
		if (returnMessageItemProvider == null) {
			returnMessageItemProvider = new ReturnMessageItemProvider(this);
		}

		return returnMessageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.Execution} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExecutionItemProvider executionItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.Execution}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExecutionAdapter() {
		if (executionItemProvider == null) {
			executionItemProvider = new ExecutionItemProvider(this);
		}

		return executionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.CombinedFragment} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CombinedFragmentItemProvider combinedFragmentItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.CombinedFragment}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCombinedFragmentAdapter() {
		if (combinedFragmentItemProvider == null) {
			combinedFragmentItemProvider = new CombinedFragmentItemProvider(this);
		}

		return combinedFragmentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.Operand} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OperandItemProvider operandItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.Operand}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOperandAdapter() {
		if (operandItemProvider == null) {
			operandItemProvider = new OperandItemProvider(this);
		}

		return operandItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.AbstractEnd} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AbstractEndItemProvider abstractEndItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.AbstractEnd}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAbstractEndAdapter() {
		if (abstractEndItemProvider == null) {
			abstractEndItemProvider = new AbstractEndItemProvider(this);
		}

		return abstractEndItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.MixEnd} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MixEndItemProvider mixEndItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.MixEnd}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMixEndAdapter() {
		if (mixEndItemProvider == null) {
			mixEndItemProvider = new MixEndItemProvider(this);
		}

		return mixEndItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.MixOpAndCFEnd} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MixOpAndCFEndItemProvider mixOpAndCFEndItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.MixOpAndCFEnd}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMixOpAndCFEndAdapter() {
		if (mixOpAndCFEndItemProvider == null) {
			mixOpAndCFEndItemProvider = new MixOpAndCFEndItemProvider(this);
		}

		return mixOpAndCFEndItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.MessageEnd} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MessageEndItemProvider messageEndItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.MessageEnd}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMessageEndAdapter() {
		if (messageEndItemProvider == null) {
			messageEndItemProvider = new MessageEndItemProvider(this);
		}

		return messageEndItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.MultiEnd} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MultiEndItemProvider multiEndItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.MultiEnd}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMultiEndAdapter() {
		if (multiEndItemProvider == null) {
			multiEndItemProvider = new MultiEndItemProvider(this);
		}

		return multiEndItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.ExecutionEnd} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExecutionEndItemProvider executionEndItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.ExecutionEnd}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExecutionEndAdapter() {
		if (executionEndItemProvider == null) {
			executionEndItemProvider = new ExecutionEndItemProvider(this);
		}

		return executionEndItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.CombinedFragmentEnd} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CombinedFragmentEndItemProvider combinedFragmentEndItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.CombinedFragmentEnd}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCombinedFragmentEndAdapter() {
		if (combinedFragmentEndItemProvider == null) {
			combinedFragmentEndItemProvider = new CombinedFragmentEndItemProvider(this);
		}

		return combinedFragmentEndItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.OperandEnd} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OperandEndItemProvider operandEndItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.OperandEnd}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOperandEndAdapter() {
		if (operandEndItemProvider == null) {
			operandEndItemProvider = new OperandEndItemProvider(this);
		}

		return operandEndItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.DomainModel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DomainModelItemProvider domainModelItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.DomainModel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDomainModelAdapter() {
		if (domainModelItemProvider == null) {
			domainModelItemProvider = new DomainModelItemProvider(this);
		}

		return domainModelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.UseCaseModel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UseCaseModelItemProvider useCaseModelItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.UseCaseModel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUseCaseModelAdapter() {
		if (useCaseModelItemProvider == null) {
			useCaseModelItemProvider = new UseCaseModelItemProvider(this);
		}

		return useCaseModelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.Actor} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ActorItemProvider actorItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.Actor}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createActorAdapter() {
		if (actorItemProvider == null) {
			actorItemProvider = new ActorItemProvider(this);
		}

		return actorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.UC} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UCItemProvider ucItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.UC}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUCAdapter() {
		if (ucItemProvider == null) {
			ucItemProvider = new UCItemProvider(this);
		}

		return ucItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.Service} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ServiceItemProvider serviceItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.Service}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createServiceAdapter() {
		if (serviceItemProvider == null) {
			serviceItemProvider = new ServiceItemProvider(this);
		}

		return serviceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.Participant} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ParticipantItemProvider participantItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.Participant}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createParticipantAdapter() {
		if (participantItemProvider == null) {
			participantItemProvider = new ParticipantItemProvider(this);
		}

		return participantItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.Workflow} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WorkflowItemProvider workflowItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.Workflow}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createWorkflowAdapter() {
		if (workflowItemProvider == null) {
			workflowItemProvider = new WorkflowItemProvider(this);
		}

		return workflowItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.Partition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PartitionItemProvider partitionItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.Partition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPartitionAdapter() {
		if (partitionItemProvider == null) {
			partitionItemProvider = new PartitionItemProvider(this);
		}

		return partitionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.WorkflowExp} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WorkflowExpItemProvider workflowExpItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.WorkflowExp}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createWorkflowExpAdapter() {
		if (workflowExpItemProvider == null) {
			workflowExpItemProvider = new WorkflowExpItemProvider(this);
		}

		return workflowExpItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.PartitionAction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PartitionActionItemProvider partitionActionItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.PartitionAction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPartitionActionAdapter() {
		if (partitionActionItemProvider == null) {
			partitionActionItemProvider = new PartitionActionItemProvider(this);
		}

		return partitionActionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.JoinExp} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected JoinExpItemProvider joinExpItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.JoinExp}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createJoinExpAdapter() {
		if (joinExpItemProvider == null) {
			joinExpItemProvider = new JoinExpItemProvider(this);
		}

		return joinExpItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.ActivityFinal} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ActivityFinalItemProvider activityFinalItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.ActivityFinal}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createActivityFinalAdapter() {
		if (activityFinalItemProvider == null) {
			activityFinalItemProvider = new ActivityFinalItemProvider(this);
		}

		return activityFinalItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.InitalNode} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InitalNodeItemProvider initalNodeItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.InitalNode}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInitalNodeAdapter() {
		if (initalNodeItemProvider == null) {
			initalNodeItemProvider = new InitalNodeItemProvider(this);
		}

		return initalNodeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.ForkNode} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ForkNodeItemProvider forkNodeItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.ForkNode}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createForkNodeAdapter() {
		if (forkNodeItemProvider == null) {
			forkNodeItemProvider = new ForkNodeItemProvider(this);
		}

		return forkNodeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.JoinNode} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected JoinNodeItemProvider joinNodeItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.JoinNode}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createJoinNodeAdapter() {
		if (joinNodeItemProvider == null) {
			joinNodeItemProvider = new JoinNodeItemProvider(this);
		}

		return joinNodeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.ComplexOpeartion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComplexOpeartionItemProvider complexOpeartionItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.ComplexOpeartion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createComplexOpeartionAdapter() {
		if (complexOpeartionItemProvider == null) {
			complexOpeartionItemProvider = new ComplexOpeartionItemProvider(this);
		}

		return complexOpeartionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.SimpleOperation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SimpleOperationItemProvider simpleOperationItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.SimpleOperation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSimpleOperationAdapter() {
		if (simpleOperationItemProvider == null) {
			simpleOperationItemProvider = new SimpleOperationItemProvider(this);
		}

		return simpleOperationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.LoopExp} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LoopExpItemProvider loopExpItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.LoopExp}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLoopExpAdapter() {
		if (loopExpItemProvider == null) {
			loopExpItemProvider = new LoopExpItemProvider(this);
		}

		return loopExpItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.SwitchExp} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SwitchExpItemProvider switchExpItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.SwitchExp}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSwitchExpAdapter() {
		if (switchExpItemProvider == null) {
			switchExpItemProvider = new SwitchExpItemProvider(this);
		}

		return switchExpItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.SwitchCase} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SwitchCaseItemProvider switchCaseItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.SwitchCase}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSwitchCaseAdapter() {
		if (switchCaseItemProvider == null) {
			switchCaseItemProvider = new SwitchCaseItemProvider(this);
		}

		return switchCaseItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.SwitchDefault} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SwitchDefaultItemProvider switchDefaultItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.SwitchDefault}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSwitchDefaultAdapter() {
		if (switchDefaultItemProvider == null) {
			switchDefaultItemProvider = new SwitchDefaultItemProvider(this);
		}

		return switchDefaultItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.Operation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OperationItemProvider operationItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.Operation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOperationAdapter() {
		if (operationItemProvider == null) {
			operationItemProvider = new OperationItemProvider(this);
		}

		return operationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.Parameter} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ParameterItemProvider parameterItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.Parameter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createParameterAdapter() {
		if (parameterItemProvider == null) {
			parameterItemProvider = new ParameterItemProvider(this);
		}

		return parameterItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.Entity} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EntityItemProvider entityItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.Entity}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEntityAdapter() {
		if (entityItemProvider == null) {
			entityItemProvider = new EntityItemProvider(this);
		}

		return entityItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.Attribute} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AttributeItemProvider attributeItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.Attribute}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAttributeAdapter() {
		if (attributeItemProvider == null) {
			attributeItemProvider = new AttributeItemProvider(this);
		}

		return attributeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.Reference} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReferenceItemProvider referenceItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.Reference}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReferenceAdapter() {
		if (referenceItemProvider == null) {
			referenceItemProvider = new ReferenceItemProvider(this);
		}

		return referenceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.TypeCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TypeCSItemProvider typeCSItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.TypeCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTypeCSAdapter() {
		if (typeCSItemProvider == null) {
			typeCSItemProvider = new TypeCSItemProvider(this);
		}

		return typeCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.Invariance} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InvarianceItemProvider invarianceItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.Invariance}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInvarianceAdapter() {
		if (invarianceItemProvider == null) {
			invarianceItemProvider = new InvarianceItemProvider(this);
		}

		return invarianceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.EntityType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EntityTypeItemProvider entityTypeItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.EntityType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEntityTypeAdapter() {
		if (entityTypeItemProvider == null) {
			entityTypeItemProvider = new EntityTypeItemProvider(this);
		}

		return entityTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.EnumEntity} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EnumEntityItemProvider enumEntityItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.EnumEntity}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEnumEntityAdapter() {
		if (enumEntityItemProvider == null) {
			enumEntityItemProvider = new EnumEntityItemProvider(this);
		}

		return enumEntityItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.EnumItem} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EnumItemItemProvider enumItemItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.EnumItem}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEnumItemAdapter() {
		if (enumItemItemProvider == null) {
			enumItemItemProvider = new EnumItemItemProvider(this);
		}

		return enumItemItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.Contract} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ContractItemProvider contractItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.Contract}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createContractAdapter() {
		if (contractItemProvider == null) {
			contractItemProvider = new ContractItemProvider(this);
		}

		return contractItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.Definition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DefinitionItemProvider definitionItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.Definition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDefinitionAdapter() {
		if (definitionItemProvider == null) {
			definitionItemProvider = new DefinitionItemProvider(this);
		}

		return definitionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.Precondition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PreconditionItemProvider preconditionItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.Precondition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPreconditionAdapter() {
		if (preconditionItemProvider == null) {
			preconditionItemProvider = new PreconditionItemProvider(this);
		}

		return preconditionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.Postcondition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PostconditionItemProvider postconditionItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.Postcondition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPostconditionAdapter() {
		if (postconditionItemProvider == null) {
			postconditionItemProvider = new PostconditionItemProvider(this);
		}

		return postconditionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.OCLExpressionCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OCLExpressionCSItemProvider oclExpressionCSItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.OCLExpressionCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOCLExpressionCSAdapter() {
		if (oclExpressionCSItemProvider == null) {
			oclExpressionCSItemProvider = new OCLExpressionCSItemProvider(this);
		}

		return oclExpressionCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.NestedExpCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NestedExpCSItemProvider nestedExpCSItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.NestedExpCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNestedExpCSAdapter() {
		if (nestedExpCSItemProvider == null) {
			nestedExpCSItemProvider = new NestedExpCSItemProvider(this);
		}

		return nestedExpCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.LogicFormulaExpCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LogicFormulaExpCSItemProvider logicFormulaExpCSItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.LogicFormulaExpCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLogicFormulaExpCSAdapter() {
		if (logicFormulaExpCSItemProvider == null) {
			logicFormulaExpCSItemProvider = new LogicFormulaExpCSItemProvider(this);
		}

		return logicFormulaExpCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.AtomicExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AtomicExpressionItemProvider atomicExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.AtomicExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAtomicExpressionAdapter() {
		if (atomicExpressionItemProvider == null) {
			atomicExpressionItemProvider = new AtomicExpressionItemProvider(this);
		}

		return atomicExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.LeftSubAtomicExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LeftSubAtomicExpressionItemProvider leftSubAtomicExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.LeftSubAtomicExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLeftSubAtomicExpressionAdapter() {
		if (leftSubAtomicExpressionItemProvider == null) {
			leftSubAtomicExpressionItemProvider = new LeftSubAtomicExpressionItemProvider(this);
		}

		return leftSubAtomicExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.RightSubAtomicExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RightSubAtomicExpressionItemProvider rightSubAtomicExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.RightSubAtomicExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRightSubAtomicExpressionAdapter() {
		if (rightSubAtomicExpressionItemProvider == null) {
			rightSubAtomicExpressionItemProvider = new RightSubAtomicExpressionItemProvider(this);
		}

		return rightSubAtomicExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.CallExpCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CallExpCSItemProvider callExpCSItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.CallExpCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCallExpCSAdapter() {
		if (callExpCSItemProvider == null) {
			callExpCSItemProvider = new CallExpCSItemProvider(this);
		}

		return callExpCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.LoopExpCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LoopExpCSItemProvider loopExpCSItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.LoopExpCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLoopExpCSAdapter() {
		if (loopExpCSItemProvider == null) {
			loopExpCSItemProvider = new LoopExpCSItemProvider(this);
		}

		return loopExpCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.IteratorExpCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IteratorExpCSItemProvider iteratorExpCSItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.IteratorExpCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIteratorExpCSAdapter() {
		if (iteratorExpCSItemProvider == null) {
			iteratorExpCSItemProvider = new IteratorExpCSItemProvider(this);
		}

		return iteratorExpCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.EntityAttributeName} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EntityAttributeNameItemProvider entityAttributeNameItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.EntityAttributeName}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEntityAttributeNameAdapter() {
		if (entityAttributeNameItemProvider == null) {
			entityAttributeNameItemProvider = new EntityAttributeNameItemProvider(this);
		}

		return entityAttributeNameItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.ArgumentsCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ArgumentsCSItemProvider argumentsCSItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.ArgumentsCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createArgumentsCSAdapter() {
		if (argumentsCSItemProvider == null) {
			argumentsCSItemProvider = new ArgumentsCSItemProvider(this);
		}

		return argumentsCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.FeatureCallExpCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FeatureCallExpCSItemProvider featureCallExpCSItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.FeatureCallExpCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFeatureCallExpCSAdapter() {
		if (featureCallExpCSItemProvider == null) {
			featureCallExpCSItemProvider = new FeatureCallExpCSItemProvider(this);
		}

		return featureCallExpCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.StandardNavigationCallExpCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StandardNavigationCallExpCSItemProvider standardNavigationCallExpCSItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.StandardNavigationCallExpCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStandardNavigationCallExpCSAdapter() {
		if (standardNavigationCallExpCSItemProvider == null) {
			standardNavigationCallExpCSItemProvider = new StandardNavigationCallExpCSItemProvider(this);
		}

		return standardNavigationCallExpCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.StandardOperationExpCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StandardOperationExpCSItemProvider standardOperationExpCSItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.StandardOperationExpCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStandardOperationExpCSAdapter() {
		if (standardOperationExpCSItemProvider == null) {
			standardOperationExpCSItemProvider = new StandardOperationExpCSItemProvider(this);
		}

		return standardOperationExpCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.PredefineOp} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PredefineOpItemProvider predefineOpItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.PredefineOp}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPredefineOpAdapter() {
		if (predefineOpItemProvider == null) {
			predefineOpItemProvider = new PredefineOpItemProvider(this);
		}

		return predefineOpItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.StandardNoneParameterOperation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StandardNoneParameterOperationItemProvider standardNoneParameterOperationItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.StandardNoneParameterOperation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStandardNoneParameterOperationAdapter() {
		if (standardNoneParameterOperationItemProvider == null) {
			standardNoneParameterOperationItemProvider = new StandardNoneParameterOperationItemProvider(this);
		}

		return standardNoneParameterOperationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.StandardParameterOperation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StandardParameterOperationItemProvider standardParameterOperationItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.StandardParameterOperation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStandardParameterOperationAdapter() {
		if (standardParameterOperationItemProvider == null) {
			standardParameterOperationItemProvider = new StandardParameterOperationItemProvider(this);
		}

		return standardParameterOperationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.StandardCollectionOperation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StandardCollectionOperationItemProvider standardCollectionOperationItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.StandardCollectionOperation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStandardCollectionOperationAdapter() {
		if (standardCollectionOperationItemProvider == null) {
			standardCollectionOperationItemProvider = new StandardCollectionOperationItemProvider(this);
		}

		return standardCollectionOperationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.StandardDateOperation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StandardDateOperationItemProvider standardDateOperationItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.StandardDateOperation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStandardDateOperationAdapter() {
		if (standardDateOperationItemProvider == null) {
			standardDateOperationItemProvider = new StandardDateOperationItemProvider(this);
		}

		return standardDateOperationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.ClassiferCallExpCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ClassiferCallExpCSItemProvider classiferCallExpCSItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.ClassiferCallExpCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createClassiferCallExpCSAdapter() {
		if (classiferCallExpCSItemProvider == null) {
			classiferCallExpCSItemProvider = new ClassiferCallExpCSItemProvider(this);
		}

		return classiferCallExpCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.PropertyCallExpCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PropertyCallExpCSItemProvider propertyCallExpCSItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.PropertyCallExpCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPropertyCallExpCSAdapter() {
		if (propertyCallExpCSItemProvider == null) {
			propertyCallExpCSItemProvider = new PropertyCallExpCSItemProvider(this);
		}

		return propertyCallExpCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.OperationCallExpCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OperationCallExpCSItemProvider operationCallExpCSItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.OperationCallExpCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOperationCallExpCSAdapter() {
		if (operationCallExpCSItemProvider == null) {
			operationCallExpCSItemProvider = new OperationCallExpCSItemProvider(this);
		}

		return operationCallExpCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.OperationParameters} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OperationParametersItemProvider operationParametersItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.OperationParameters}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOperationParametersAdapter() {
		if (operationParametersItemProvider == null) {
			operationParametersItemProvider = new OperationParametersItemProvider(this);
		}

		return operationParametersItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.VariableExpCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VariableExpCSItemProvider variableExpCSItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.VariableExpCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createVariableExpCSAdapter() {
		if (variableExpCSItemProvider == null) {
			variableExpCSItemProvider = new VariableExpCSItemProvider(this);
		}

		return variableExpCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.IfExpCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IfExpCSItemProvider ifExpCSItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.IfExpCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIfExpCSAdapter() {
		if (ifExpCSItemProvider == null) {
			ifExpCSItemProvider = new IfExpCSItemProvider(this);
		}

		return ifExpCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.LetExpCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LetExpCSItemProvider letExpCSItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.LetExpCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLetExpCSAdapter() {
		if (letExpCSItemProvider == null) {
			letExpCSItemProvider = new LetExpCSItemProvider(this);
		}

		return letExpCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.VariableDeclarationCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VariableDeclarationCSItemProvider variableDeclarationCSItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.VariableDeclarationCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createVariableDeclarationCSAdapter() {
		if (variableDeclarationCSItemProvider == null) {
			variableDeclarationCSItemProvider = new VariableDeclarationCSItemProvider(this);
		}

		return variableDeclarationCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.LiteralExpCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LiteralExpCSItemProvider literalExpCSItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.LiteralExpCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLiteralExpCSAdapter() {
		if (literalExpCSItemProvider == null) {
			literalExpCSItemProvider = new LiteralExpCSItemProvider(this);
		}

		return literalExpCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.EnumLiteralExpCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EnumLiteralExpCSItemProvider enumLiteralExpCSItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.EnumLiteralExpCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEnumLiteralExpCSAdapter() {
		if (enumLiteralExpCSItemProvider == null) {
			enumLiteralExpCSItemProvider = new EnumLiteralExpCSItemProvider(this);
		}

		return enumLiteralExpCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.TupleLiteralExpCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TupleLiteralExpCSItemProvider tupleLiteralExpCSItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.TupleLiteralExpCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTupleLiteralExpCSAdapter() {
		if (tupleLiteralExpCSItemProvider == null) {
			tupleLiteralExpCSItemProvider = new TupleLiteralExpCSItemProvider(this);
		}

		return tupleLiteralExpCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.TupleTypeCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TupleTypeCSItemProvider tupleTypeCSItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.TupleTypeCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTupleTypeCSAdapter() {
		if (tupleTypeCSItemProvider == null) {
			tupleTypeCSItemProvider = new TupleTypeCSItemProvider(this);
		}

		return tupleTypeCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.CollectionTypeCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CollectionTypeCSItemProvider collectionTypeCSItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.CollectionTypeCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCollectionTypeCSAdapter() {
		if (collectionTypeCSItemProvider == null) {
			collectionTypeCSItemProvider = new CollectionTypeCSItemProvider(this);
		}

		return collectionTypeCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.CollectionLiteralExpCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CollectionLiteralExpCSItemProvider collectionLiteralExpCSItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.CollectionLiteralExpCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCollectionLiteralExpCSAdapter() {
		if (collectionLiteralExpCSItemProvider == null) {
			collectionLiteralExpCSItemProvider = new CollectionLiteralExpCSItemProvider(this);
		}

		return collectionLiteralExpCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.CollectionLiteralPartCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CollectionLiteralPartCSItemProvider collectionLiteralPartCSItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.CollectionLiteralPartCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCollectionLiteralPartCSAdapter() {
		if (collectionLiteralPartCSItemProvider == null) {
			collectionLiteralPartCSItemProvider = new CollectionLiteralPartCSItemProvider(this);
		}

		return collectionLiteralPartCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.CollectionRangeCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CollectionRangeCSItemProvider collectionRangeCSItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.CollectionRangeCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCollectionRangeCSAdapter() {
		if (collectionRangeCSItemProvider == null) {
			collectionRangeCSItemProvider = new CollectionRangeCSItemProvider(this);
		}

		return collectionRangeCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.CollectionItem} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CollectionItemItemProvider collectionItemItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.CollectionItem}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCollectionItemAdapter() {
		if (collectionItemItemProvider == null) {
			collectionItemItemProvider = new CollectionItemItemProvider(this);
		}

		return collectionItemItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.PrimitiveLiteralExpCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PrimitiveLiteralExpCSItemProvider primitiveLiteralExpCSItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.PrimitiveLiteralExpCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPrimitiveLiteralExpCSAdapter() {
		if (primitiveLiteralExpCSItemProvider == null) {
			primitiveLiteralExpCSItemProvider = new PrimitiveLiteralExpCSItemProvider(this);
		}

		return primitiveLiteralExpCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.NumberLiteralExpCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NumberLiteralExpCSItemProvider numberLiteralExpCSItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.NumberLiteralExpCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNumberLiteralExpCSAdapter() {
		if (numberLiteralExpCSItemProvider == null) {
			numberLiteralExpCSItemProvider = new NumberLiteralExpCSItemProvider(this);
		}

		return numberLiteralExpCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.BooleanLiteralExpCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BooleanLiteralExpCSItemProvider booleanLiteralExpCSItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.BooleanLiteralExpCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBooleanLiteralExpCSAdapter() {
		if (booleanLiteralExpCSItemProvider == null) {
			booleanLiteralExpCSItemProvider = new BooleanLiteralExpCSItemProvider(this);
		}

		return booleanLiteralExpCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.StringLiteralExpCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StringLiteralExpCSItemProvider stringLiteralExpCSItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.StringLiteralExpCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStringLiteralExpCSAdapter() {
		if (stringLiteralExpCSItemProvider == null) {
			stringLiteralExpCSItemProvider = new StringLiteralExpCSItemProvider(this);
		}

		return stringLiteralExpCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.NullLiteralExpCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NullLiteralExpCSItemProvider nullLiteralExpCSItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.NullLiteralExpCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNullLiteralExpCSAdapter() {
		if (nullLiteralExpCSItemProvider == null) {
			nullLiteralExpCSItemProvider = new NullLiteralExpCSItemProvider(this);
		}

		return nullLiteralExpCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.InvalidLiteralExpCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InvalidLiteralExpCSItemProvider invalidLiteralExpCSItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.InvalidLiteralExpCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInvalidLiteralExpCSAdapter() {
		if (invalidLiteralExpCSItemProvider == null) {
			invalidLiteralExpCSItemProvider = new InvalidLiteralExpCSItemProvider(this);
		}

		return invalidLiteralExpCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.ReservedKeywordCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReservedKeywordCSItemProvider reservedKeywordCSItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.ReservedKeywordCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReservedKeywordCSAdapter() {
		if (reservedKeywordCSItemProvider == null) {
			reservedKeywordCSItemProvider = new ReservedKeywordCSItemProvider(this);
		}

		return reservedKeywordCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.CollectionTypeIdentifierCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CollectionTypeIdentifierCSItemProvider collectionTypeIdentifierCSItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.CollectionTypeIdentifierCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCollectionTypeIdentifierCSAdapter() {
		if (collectionTypeIdentifierCSItemProvider == null) {
			collectionTypeIdentifierCSItemProvider = new CollectionTypeIdentifierCSItemProvider(this);
		}

		return collectionTypeIdentifierCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.PrimitiveTypeCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PrimitiveTypeCSItemProvider primitiveTypeCSItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.PrimitiveTypeCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPrimitiveTypeCSAdapter() {
		if (primitiveTypeCSItemProvider == null) {
			primitiveTypeCSItemProvider = new PrimitiveTypeCSItemProvider(this);
		}

		return primitiveTypeCSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link rEMODEL.OclTypeCS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OclTypeCSItemProvider oclTypeCSItemProvider;

	/**
	 * This creates an adapter for a {@link rEMODEL.OclTypeCS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOclTypeCSAdapter() {
		if (oclTypeCSItemProvider == null) {
			oclTypeCSItemProvider = new OclTypeCSItemProvider(this);
		}

		return oclTypeCSItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>) type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

}
